import { Prisma } from "@/config/db/prisma";

async function main() {
  await Prisma.typeArea.createMany({
    data: [
      { name: "Sala", icon: "living", color: "#EDDDDF" },
      { name: "Habitación", icon: "bed", color: "#6831DD" },
      { name: "Oficina", icon: "work-outline", color: "#D6EBF2" },
      { name: "Cocina", icon: "kitchen", color: "#ffb3ba" },
      { name: "Baño", icon: "bathroom", color: "#c9c9ff" },
      { name: "Jardín", icon: "forest", color: "#baffc9" },
      { name: "Patio", icon: "forest", color: "#f5f5f5" },
      { name: "Zona exterior", icon: "deck", color: "#bfbfbf" },
      { name: "Garaje", icon: "garage", color: "#ffdfba" },
      { name: "Sótano", icon: "basement", color: "#f5f5f5" },
      { name: "Desván", icon: "attic", color: "#f5f5f5" },
      { name: "Cuarto de lavado", icon: "laundry", color: "#f5f5f5" },
      { name: "Cuarto de herramientas", icon: "tools", color: "#f5f5f5" },
      { name: "Cuarto de juegos", icon: "games", color: "#f5f5f5" },
    ],
  });

  await Prisma.typeController.createMany({
    data: [
      { key: "arduino", name: "Arduino" },
      { key: "esp-8266", name: "ESP8266" },
      { key: "esp-32", name: "ESP32" },
      { key: "esp-32-cam", name: "ESP32-CAM" },
      { key: "raspberry-pi", name: "Raspberry PI" },
      { key: "raspberry-pi-pico", name: "Raspberry PI Pico" },
    ],
  });

  const devicesTypes = [
    { key: "switch", name: "Switch" },
    { key: "connector", name: "Connector" },
    { key: "dimmer", name: "Dimmer" },
    { key: "relay", name: "Relé" },
    { key: "sensor", name: "Sensor" },
    { key: "motor", name: "Motor DC" },
    { key: "servo", name: "Servomotor" },
    { key: "temperature", name: "Sensor de temperatura" },
    { key: "humidity", name: "Sensor de humedad" },
    { key: "light", name: "Sensor de luz" },
    { key: "motion", name: "Sensor de movimiento" },
    { key: "distance", name: "Sensor de distancia" },
    { key: "gas", name: "Sensor de gas" },
    { key: "sound", name: "Sensor de sonido" },
    { key: "pressure", name: "Sensor de presión" },
    { key: "current", name: "Sensor de corriente" },
    { key: "voltage", name: "Sensor de voltaje" },
    { key: "power", name: "Sensor de potencia" },
    { key: "speaker", name: "Altavoz" },
    { key: "display", name: "Pantalla" },
    { key: "led", name: "LED" },
    { key: "led-matrix", name: "Matriz de LED" },
    { key: "rgb-led", name: "LED RGB" },
    { key: "rgb-strip", name: "Tira de LED RGB" },
  ].sort((a, b) => a.name.localeCompare(b.key));

  await Prisma.typeDevice.createMany({
    data: [...devicesTypes],
  });

  const countries = [
    { name: "Afganistán", code: "AF", prefix: "+93", currencyCode: "AFN" },
    { name: "Albania", code: "AL", prefix: "+355", currencyCode: "ALL" },
    { name: "Alemania", code: "DE", prefix: "+49", currencyCode: "EUR" },
    { name: "Andorra", code: "AD", prefix: "+376", currencyCode: "EUR" },
    { name: "Angola", code: "AO", prefix: "+244", currencyCode: "AOA" },
    {
      name: "Antigua y Barbuda",
      code: "AG",
      prefix: "+1-268",
      currencyCode: "XCD",
    },
    { name: "Arabia Saudita", code: "SA", prefix: "+966", currencyCode: "SAR" },
    { name: "Argelia", code: "DZ", prefix: "+213", currencyCode: "DZD" },
    { name: "Argentina", code: "AR", prefix: "+54", currencyCode: "ARS" },
    { name: "Armenia", code: "AM", prefix: "+374", currencyCode: "AMD" },
    { name: "Australia", code: "AU", prefix: "+61", currencyCode: "AUD" },
    { name: "Austria", code: "AT", prefix: "+43", currencyCode: "EUR" },
    { name: "Azerbaiyán", code: "AZ", prefix: "+994", currencyCode: "AZN" },
    { name: "Bahamas", code: "BS", prefix: "+1-242", currencyCode: "BSD" },
    { name: "Bangladés", code: "BD", prefix: "+880", currencyCode: "BDT" },
    { name: "Barbados", code: "BB", prefix: "+1-246", currencyCode: "BBD" },
    { name: "Baréin", code: "BH", prefix: "+973", currencyCode: "BHD" },
    { name: "Bélgica", code: "BE", prefix: "+32", currencyCode: "EUR" },
    { name: "Belice", code: "BZ", prefix: "+501", currencyCode: "BZD" },
    { name: "Benín", code: "BJ", prefix: "+229", currencyCode: "XOF" },
    { name: "Bielorrusia", code: "BY", prefix: "+375", currencyCode: "BYN" },
    { name: "Birmania", code: "MM", prefix: "+95", currencyCode: "MMK" },
    { name: "Bolivia", code: "BO", prefix: "+591", currencyCode: "BOB" },
    {
      name: "Bosnia y Herzegovina",
      code: "BA",
      prefix: "+387",
      currencyCode: "BAM",
    },
    { name: "Botsuana", code: "BW", prefix: "+267", currencyCode: "BWP" },
    { name: "Brasil", code: "BR", prefix: "+55", currencyCode: "BRL" },
    { name: "Brunéi", code: "BN", prefix: "+673", currencyCode: "BND" },
    { name: "Bulgaria", code: "BG", prefix: "+359", currencyCode: "BGN" },
    { name: "Burkina Faso", code: "BF", prefix: "+226", currencyCode: "XOF" },
    { name: "Burundi", code: "BI", prefix: "+257", currencyCode: "BIF" },
    { name: "Bután", code: "BT", prefix: "+975", currencyCode: "BTN" },
    { name: "Cabo Verde", code: "CV", prefix: "+238", currencyCode: "CVE" },
    { name: "Camboya", code: "KH", prefix: "+855", currencyCode: "KHR" },
    { name: "Camerún", code: "CM", prefix: "+237", currencyCode: "XAF" },
    { name: "Canadá", code: "CA", prefix: "+1", currencyCode: "CAD" },
    { name: "Catar", code: "QA", prefix: "+974", currencyCode: "QAR" },
    { name: "Chad", code: "TD", prefix: "+235", currencyCode: "XAF" },
    { name: "Chile", code: "CL", prefix: "+56", currencyCode: "CLP" },
    { name: "China", code: "CN", prefix: "+86", currencyCode: "CNY" },
    { name: "Chipre", code: "CY", prefix: "+357", currencyCode: "EUR" },
    { name: "Colombia", code: "CO", prefix: "+57", currencyCode: "COP" },
    { name: "Comoras", code: "KM", prefix: "+269", currencyCode: "KMF" },
    {
      name: "Corea del Norte",
      code: "KP",
      prefix: "+850",
      currencyCode: "KPW",
    },
    { name: "Corea del Sur", code: "KR", prefix: "+82", currencyCode: "KRW" },
    {
      name: "Costa de Marfil",
      code: "CI",
      prefix: "+225",
      currencyCode: "XOF",
    },
    { name: "Costa Rica", code: "CR", prefix: "+506", currencyCode: "CRC" },
    { name: "Croacia", code: "HR", prefix: "+385", currencyCode: "EUR" },
    { name: "Cuba", code: "CU", prefix: "+53", currencyCode: "CUP" },
    { name: "Dinamarca", code: "DK", prefix: "+45", currencyCode: "DKK" },
    { name: "Dominica", code: "DM", prefix: "+1-767", currencyCode: "XCD" },
    { name: "Ecuador", code: "EC", prefix: "+593", currencyCode: "USD" },
    { name: "Egipto", code: "EG", prefix: "+20", currencyCode: "EGP" },
    { name: "El Salvador", code: "SV", prefix: "+503", currencyCode: "USD" },
    {
      name: "Emiratos Árabes Unidos",
      code: "AE",
      prefix: "+971",
      currencyCode: "AED",
    },
    { name: "Eritrea", code: "ER", prefix: "+291", currencyCode: "ERN" },
    { name: "Eslovaquia", code: "SK", prefix: "+421", currencyCode: "EUR" },
    { name: "Eslovenia", code: "SI", prefix: "+386", currencyCode: "EUR" },
    { name: "España", code: "ES", prefix: "+34", currencyCode: "EUR" },
    { name: "Estados Unidos", code: "US", prefix: "+1", currencyCode: "USD" },
    { name: "Estonia", code: "EE", prefix: "+372", currencyCode: "EUR" },
    { name: "Etiopía", code: "ET", prefix: "+251", currencyCode: "ETB" },
    { name: "Filipinas", code: "PH", prefix: "+63", currencyCode: "PHP" },
    { name: "Finlandia", code: "FI", prefix: "+358", currencyCode: "EUR" },
    { name: "Fiyi", code: "FJ", prefix: "+679", currencyCode: "FJD" },
    { name: "Francia", code: "FR", prefix: "+33", currencyCode: "EUR" },
    { name: "Gabón", code: "GA", prefix: "+241", currencyCode: "XAF" },
    { name: "Gambia", code: "GM", prefix: "+220", currencyCode: "GMD" },
    { name: "Georgia", code: "GE", prefix: "+995", currencyCode: "GEL" },
    { name: "Ghana", code: "GH", prefix: "+233", currencyCode: "GHS" },
    { name: "Grecia", code: "GR", prefix: "+30", currencyCode: "EUR" },
    { name: "Guatemala", code: "GT", prefix: "+502", currencyCode: "GTQ" },
    { name: "Guinea", code: "GN", prefix: "+224", currencyCode: "GNF" },
    { name: "Guinea-Bisáu", code: "GW", prefix: "+245", currencyCode: "XOF" },
    {
      name: "Guinea Ecuatorial",
      code: "GQ",
      prefix: "+240",
      currencyCode: "XAF",
    },
    { name: "Guyana", code: "GY", prefix: "+592", currencyCode: "GYD" },
    { name: "Haití", code: "HT", prefix: "+509", currencyCode: "HTG" },
    { name: "Honduras", code: "HN", prefix: "+504", currencyCode: "HNL" },
    { name: "Hungría", code: "HU", prefix: "+36", currencyCode: "HUF" },
    { name: "India", code: "IN", prefix: "+91", currencyCode: "INR" },
    { name: "Indonesia", code: "ID", prefix: "+62", currencyCode: "IDR" },
    { name: "Irak", code: "IQ", prefix: "+964", currencyCode: "IQD" },
    { name: "Irlanda", code: "IE", prefix: "+353", currencyCode: "EUR" },
    { name: "Islas Marshall", code: "MH", prefix: "+692", currencyCode: "USD" },
    { name: "Islandia", code: "IS", prefix: "+354", currencyCode: "ISK" },
    { name: "Islas Salomón", code: "SB", prefix: "+677", currencyCode: "SBD" },
    {
      name: "Islas Vírgenes Británicas",
      code: "VG",
      prefix: "+1-284",
      currencyCode: "USD",
    },
    {
      name: "Islas Vírgenes de los EE. UU.",
      code: "VI",
      prefix: "+1-340",
      currencyCode: "USD",
    },
    { name: "Israel", code: "IL", prefix: "+972", currencyCode: "ILS" },
    { name: "Italia", code: "IT", prefix: "+39", currencyCode: "EUR" },
    { name: "Jamaica", code: "JM", prefix: "+1-876", currencyCode: "JMD" },
    { name: "Japón", code: "JP", prefix: "+81", currencyCode: "JPY" },
    { name: "Jordania", code: "JO", prefix: "+962", currencyCode: "JOD" },
    { name: "Kazajistán", code: "KZ", prefix: "+7", currencyCode: "KZT" },
    { name: "Kenia", code: "KE", prefix: "+254", currencyCode: "KES" },
    { name: "Kirguistán", code: "KG", prefix: "+996", currencyCode: "KGS" },
    { name: "Kiribati", code: "KI", prefix: "+686", currencyCode: "AUD" },
    { name: "Laos", code: "LA", prefix: "+856", currencyCode: "LAK" },
    { name: "Latvia", code: "LV", prefix: "+371", currencyCode: "EUR" },
    { name: "Líbano", code: "LB", prefix: "+961", currencyCode: "LBP" },
    { name: "Lesoto", code: "LS", prefix: "+266", currencyCode: "LSL" },
    { name: "Liberia", code: "LR", prefix: "+231", currencyCode: "LRD" },
    { name: "Libia", code: "LY", prefix: "+218", currencyCode: "LYD" },
    { name: "Liechtenstein", code: "LI", prefix: "+423", currencyCode: "CHF" },
    { name: "Lituania", code: "LT", prefix: "+370", currencyCode: "EUR" },
    { name: "Luxemburgo", code: "LU", prefix: "+352", currencyCode: "EUR" },
    { name: "Madagascar", code: "MG", prefix: "+261", currencyCode: "MGA" },
    { name: "Malasia", code: "MY", prefix: "+60", currencyCode: "MYR" },
    { name: "Malawi", code: "MW", prefix: "+265", currencyCode: "MWK" },
    { name: "Maldivas", code: "MV", prefix: "+960", currencyCode: "MVR" },
    { name: "Malta", code: "MT", prefix: "+356", currencyCode: "EUR" },
    { name: "Marruecos", code: "MA", prefix: "+212", currencyCode: "MAD" },
    { name: "Mauricio", code: "MU", prefix: "+230", currencyCode: "MUR" },
    { name: "Mauritania", code: "MR", prefix: "+222", currencyCode: "MRU" },
    { name: "México", code: "MX", prefix: "+52", currencyCode: "MXN" },
    { name: "Micronesia", code: "FM", prefix: "+691", currencyCode: "USD" },
    { name: "Moldavia", code: "MD", prefix: "+373", currencyCode: "MDL" },
    { name: "Mónaco", code: "MC", prefix: "+377", currencyCode: "EUR" },
    { name: "Mongolia", code: "MN", prefix: "+976", currencyCode: "MNT" },
    { name: "Montenegro", code: "ME", prefix: "+382", currencyCode: "EUR" },
    { name: "Morocco", code: "MR", prefix: "+222", currencyCode: "MRU" },
    { name: "Mozambique", code: "MZ", prefix: "+258", currencyCode: "MZN" },
    { name: "Namibia", code: "NA", prefix: "+264", currencyCode: "NAD" },
    { name: "Nauru", code: "NR", prefix: "+674", currencyCode: "AUD" },
    { name: "Nepal", code: "NP", prefix: "+977", currencyCode: "NPR" },
    { name: "Nicaragua", code: "NI", prefix: "+505", currencyCode: "NIO" },
    { name: "Níger", code: "NE", prefix: "+227", currencyCode: "XOF" },
    { name: "Nigeria", code: "NG", prefix: "+234", currencyCode: "NGN" },
    { name: "Noruega", code: "NO", prefix: "+47", currencyCode: "NOK" },
    { name: "Nueva Zelanda", code: "NZ", prefix: "+64", currencyCode: "NZD" },
    { name: "Omán", code: "OM", prefix: "+968", currencyCode: "OMR" },
    { name: "Países Bajos", code: "NL", prefix: "+31", currencyCode: "EUR" },
    { name: "Pakistán", code: "PK", prefix: "+92", currencyCode: "PKR" },
    { name: "Palaos", code: "PW", prefix: "+680", currencyCode: "USD" },
    { name: "Panamá", code: "PA", prefix: "+507", currencyCode: "PAB" },
    {
      name: "Papúa Nueva Guinea",
      code: "PG",
      prefix: "+675",
      currencyCode: "PGK",
    },
    { name: "Paraguay", code: "PY", prefix: "+595", currencyCode: "PYG" },
    { name: "Perú", code: "PE", prefix: "+51", currencyCode: "PEN" },
    { name: "Polonia", code: "PL", prefix: "+48", currencyCode: "PLN" },
    { name: "Portugal", code: "PT", prefix: "+351", currencyCode: "EUR" },
    { name: "Ruanda", code: "RW", prefix: "+250", currencyCode: "RWF" },
    { name: "Rumanía", code: "RO", prefix: "+40", currencyCode: "RON" },
    { name: "Rusia", code: "RU", prefix: "+7", currencyCode: "RUB" },
    {
      name: "San Cristóbal y Nieves",
      code: "KN",
      prefix: "+1-869",
      currencyCode: "XCD",
    },
    { name: "San Marino", code: "SM", prefix: "+378", currencyCode: "EUR" },
    {
      name: "San Tomé y Príncipe",
      code: "ST",
      prefix: "+239",
      currencyCode: "STN",
    },
    { name: "Santa Lucía", code: "LC", prefix: "+1-758", currencyCode: "XCD" },
    { name: "Senegal", code: "SN", prefix: "+221", currencyCode: "XOF" },
    { name: "Serbia", code: "RS", prefix: "+381", currencyCode: "RSD" },
    { name: "Seychelles", code: "SC", prefix: "+248", currencyCode: "SCR" },
    { name: "Sierra Leona", code: "SL", prefix: "+232", currencyCode: "SLL" },
    { name: "Singapur", code: "SG", prefix: "+65", currencyCode: "SGD" },
    { name: "Siria", code: "SY", prefix: "+963", currencyCode: "SYP" },
    { name: "Somalia", code: "SO", prefix: "+252", currencyCode: "SOS" },
    { name: "Sri Lanka", code: "LK", prefix: "+94", currencyCode: "LKR" },
    { name: "Suazilandia", code: "SZ", prefix: "+268", currencyCode: "SZL" },
    { name: "Sudán", code: "SD", prefix: "+249", currencyCode: "SDG" },
    { name: "Suecia", code: "SE", prefix: "+46", currencyCode: "SEK" },
    { name: "Suiza", code: "CH", prefix: "+41", currencyCode: "CHF" },
    { name: "Surinam", code: "SR", prefix: "+597", currencyCode: "SRD" },
    { name: "Tailandia", code: "TH", prefix: "+66", currencyCode: "THB" },
    { name: "Timor Oriental", code: "TL", prefix: "+670", currencyCode: "USD" },
    { name: "Togo", code: "TG", prefix: "+228", currencyCode: "XOF" },
    { name: "Tonga", code: "TO", prefix: "+676", currencyCode: "TOP" },
    {
      name: "Trinidad y Tobago",
      code: "TT",
      prefix: "+1-868",
      currencyCode: "TTD",
    },
    { name: "Túnez", code: "TN", prefix: "+216", currencyCode: "TND" },
    { name: "Turkmenistán", code: "TM", prefix: "+993", currencyCode: "TMT" },
    { name: "Turquía", code: "TR", prefix: "+90", currencyCode: "TRY" },
    { name: "Tuvalu", code: "TV", prefix: "+688", currencyCode: "AUD" },
    { name: "Ucrania", code: "UA", prefix: "+380", currencyCode: "UAH" },
    { name: "Uganda", code: "UG", prefix: "+256", currencyCode: "UGX" },
    { name: "Uruguay", code: "UY", prefix: "+598", currencyCode: "UYU" },
    { name: "Uzbekistán", code: "UZ", prefix: "+998", currencyCode: "UZS" },
    { name: "Vanuatu", code: "VU", prefix: "+678", currencyCode: "VUV" },
    { name: "Vaticano", code: "VA", prefix: "+379", currencyCode: "EUR" },
    { name: "Venezuela", code: "VE", prefix: "+58", currencyCode: "VES" },
    { name: "Vietnam", code: "VN", prefix: "+84", currencyCode: "VND" },
    { name: "Yemen", code: "YE", prefix: "+967", currencyCode: "YER" },
    { name: "Zambia", code: "ZM", prefix: "+260", currencyCode: "ZMW" },
    { name: "Zimbabue", code: "ZW", prefix: "+263", currencyCode: "ZWL" },
  ];
  await Prisma.country.createMany({
    data: [...countries],
  });
}
main()
  .then(async () => await Prisma.$disconnect())
  .catch(async (e) => {
    console.error(e);
    await Prisma.$disconnect();
    process.exit(1);
  });
