import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Proyectos / IoTouch",
  description: "Generated by create next app",
};

export default function Projects() {
  return (
    <>
      <div>Proyectos</div>
    </>
  );
}
